/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.CT_HoaDon_DAO;
import DTO.CT_HoaDon_DTO;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class CTHoadon_GUI extends javax.swing.JFrame {

    /**
     * Creates new form CTHoadon_GUI
     */
    private String maDon = "";
    private String maKH = "";
    private String maNV = "";
    private String ngayThanhToan = "";
    private String tongSach = "";
    private String tongTien = "";
  
    DefaultTableModel model;
    DefaultTableColumnModel modelColumn;
    public CTHoadon_GUI(String maDon, String maKH, String maNV, String ngayThanhToan, String tongSach, String tongTien) {
        this.maDon = maDon;
        this.maKH = maKH;
        this.maNV = maNV;
        this.ngayThanhToan = ngayThanhToan;
        this.tongSach = tongSach;
        this.tongTien = tongTien;
//        this.HD = HD;
        
        initComponents();
        this.model = (DefaultTableModel)table_CT.getModel();
        this.modelColumn = (DefaultTableColumnModel)table_CT.getColumnModel();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Chi tiết đơn hàng");
        
        label_maDon.setHorizontalAlignment(SwingConstants.CENTER);
        label_maDon.setHorizontalTextPosition(SwingConstants.CENTER);
        
        label_maDon.setText("Đơn: " + maDon);
        text_NhanVien.setText(maNV);
        text_khachHang.setText(maKH);
        text_tongSach.setText(tongSach);
        text_NgayThanhToan.setText(ngayThanhToan);
        text_tongThanhTien.setText(tongTien);
        
        this.loadTableCT_HD();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        text_NhanVien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_NgayThanhToan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_khachHang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_tongSach = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        text_tongThanhTien = new javax.swing.JTextField();
        label_maDon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_CT = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("THÔNG TIN LIÊN QUAN"));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nhân viên:");

        text_NhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_NhanVien.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ngày thanh toán:");

        text_NgayThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_NgayThanhToan.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Khách hàng:");

        text_khachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_khachHang.setFocusable(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tổng số sách:");

        text_tongSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_tongSach.setFocusable(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tổng thành tiền:");

        text_tongThanhTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_tongThanhTien.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_khachHang)
                    .addComponent(text_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(text_NgayThanhToan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_tongSach, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_tongThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(text_tongSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_NgayThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(text_tongThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_khachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        label_maDon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_maDon.setForeground(new java.awt.Color(0, 102, 204));
        label_maDon.setText("jLabel1");

        table_CT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_CT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_CT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_maDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_maDon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void defineColumnTable(){
        this.model.setColumnIdentifiers(new String[]{
            "Mã đơn", "Mã sách", "Số lượng", "Giảm giá", "Tổng tiền"
        });
        
        this.modelColumn.getColumn(1).setPreferredWidth(100);
        this.modelColumn.getColumn(2).setPreferredWidth(100);
        this.modelColumn.getColumn(1).setPreferredWidth(150);
        this.modelColumn.getColumn(1).setPreferredWidth(100);
        this.modelColumn.getColumn(1).setPreferredWidth(150);
        
        table_CT.getTableHeader().setFont(new Font("Aria", Font.BOLD, 16));
    }
    
    private void loadTableCT_HD(){
        this.defineColumnTable();
        DefaultTableModel model = (DefaultTableModel)table_CT.getModel();
        model.setRowCount(0);
        ArrayList<CT_HoaDon_DTO> l_CT_HoaDon = CT_HoaDon_DAO.getCT_HoaDon(this.maDon);
        for(CT_HoaDon_DTO CT : l_CT_HoaDon){
            model.addRow(new String[]{
                String.valueOf(CT.getMaHoaDon()),
                String.valueOf(CT.getMaSach()),
                String.valueOf(CT.getSoLuong()),
                CT.getGiamGia(),
                String.valueOf(CT.getTongTien())
            });
        }
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//        this.HD.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_maDon;
    private javax.swing.JTable table_CT;
    private javax.swing.JTextField text_NgayThanhToan;
    private javax.swing.JTextField text_NhanVien;
    private javax.swing.JTextField text_khachHang;
    private javax.swing.JTextField text_tongSach;
    private javax.swing.JTextField text_tongThanhTien;
    // End of variables declaration//GEN-END:variables
}
